---
- name: Enable ip forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: true

- name: Create warp user
  ansible.builtin.user:
    name: warp
    system: true
    shell: /usr/sbin/nologin
    comment: "Cloudflare WARP service user"

- name: Ensure warp-svc is enabled and running
  ansible.builtin.service:
    name: warp-svc
    enabled: true
    state: started

- name: Check warp registration
  ansible.builtin.command: warp-cli --accept-tos registration show
  register: warp_connector_registration
  changed_when: false
  failed_when: false

- name: Register warp connector with cloudflare
  ansible.builtin.command:
    cmd: "warp-cli --accept-tos connector new {{ warp_connector_token }}"
  when: warp_connector_registration.rc != 0
  changed_when: true
  no_log: true

- name: Check warp connection status
  ansible.builtin.command: warp-cli --accept-tos status
  register: warp_connector_status
  changed_when: false

- name: Connect warp
  ansible.builtin.command:
    cmd: warp-cli --accept-tos connect
  when: "'Connected' not in warp_connector_status.stdout"
  changed_when: true
