---
# step1: determine arm64 vs amd64 -> {{ target_arch }}
# step2:
#   for item in talos_versions: download vmlinuz
#     https://github.com/siderolabs/talos/releases/download/{{ item }}/vmlinuz-{{ target_arch }}
#     https://github.com/siderolabs/talos/releases/download/{{ item }}/initramfs-{{ target_arch }}.xz

- name: Install talos directories
  ansible.builtin.file:
    path: "{{ pxe_tftp_boot_path }}/talos/{{ talos_linux_version }}/{{ item }}"
    state: directory
    mode: "0755"
  loop: "{{ pxe_talos_architectures }}"
  notify: Restart tftpd

- name: Download talos vmlinuz
  ansible.builtin.get_url:
    url: "https://github.com/siderolabs/talos/releases/download/{{ talos_linux_version }}/vmlinuz-{{ item }}"
    dest: "{{ pxe_tftp_boot_path }}/talos/{{ talos_linux_version }}/{{ item }}/vmlinuz"
    mode: "0644"
  loop: "{{ pxe_talos_architectures }}"
  notify: Restart tftpd

- name: Ensure vmlinuz is world readable
  ansible.builtin.file:
    path: "{{ pxe_tftp_boot_path }}/talos/{{ talos_linux_version }}/{{ item }}/vmlinuz"
    mode: "0644"
  loop: "{{ pxe_talos_architectures }}"
  notify: Restart tftpd

- name: Download talos initramfs
  ansible.builtin.get_url:
    url: "https://github.com/siderolabs/talos/releases/download/{{ talos_linux_version }}/initramfs-{{ item }}.xz"
    dest: "{{ pxe_tftp_boot_path }}/talos/{{ talos_linux_version }}/{{ item }}/initramfs.xz"
    mode: "0644"
  loop: "{{ pxe_talos_architectures }}"
  notify: Restart tftpd

- name: Ensure initramfs is world readable
  ansible.builtin.file:
    path: "{{ pxe_tftp_boot_path }}/talos/{{ talos_linux_version }}/{{ item }}/initramfs.xz"
    mode: "0644"
  loop: "{{ pxe_talos_architectures }}"
  notify: Restart tftpd
