---
all:
  children:
    proxmox:
      hosts:
        proxmox-1:
          ansible_host: 192.168.10.11
        proxmox-2:
          ansible_host: 192.168.10.12
        proxmox-3:
          ansible_host: 192.168.10.13
    dns_lb:
      hosts:
        ns1:
          ansible_host: 192.168.1.3
        ns2:
          ansible_host: 192.168.1.4
    pxe:
      hosts:
        pxe-server:
          ansible_host: 192.168.10.4
    warp:
      hosts:
        ns1:
