- name: enable ip forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: true

- name: create warp user
  ansible.builtin.user:
    name: warp
    system: true
    shell: /usr/sbin/nologin
    comment: "Cloudflare WARP service user"

- name: ensure warp-svc is enabled and running
  ansible.builtin.service:
    name: warp-svc
    enabled: true
    state: started

- name: register warp connector with cloudflare
  ansible.builtin.command:
    cmd: "warp-cli --accept-tos connector new {{ warp_connector_token }}"

- name: connect warp
  ansible.builtin.command:
    cmd: "warp-cli connect"

