---

- name: install prerequisite packages
  ansible.builtin.apt:
    pkg: "{{ packages }}"
    update_cache: true

- name: download cloudflare warp gpg key
  ansible.builtin.get_url:
    url: "{{ warp_gpg_url }}"
    dest: "{{ warp_gpg_tmp }}"
    mode: "644"

- name: dearmor cloudflare warp gpg key
  ansible.builtin.command:
    cmd: "gpg --yes --dearmor --output {{ warp_gpg_dest }} {{ warp_gpg_tmp }}"
    creates: "{{ warp_gpg_dest }}"

- name: add cloudflare warp apt repository
  ansible.builtin.copy:
    content: "deb [arch=amd64 signed-by={{ warp_gpg_dest }}] https://pkg.cloudflareclient.com/ {{ ansible_distribution_release }} main\n"
    dest: "{{ warp_apt_file }}"
    mode: "644"
  notify: update apt cache

- name: flush handlers
  ansible.builtin.meta: flush_handlers

- name: install cloudflare-warp
  ansible.builtin.apt:
    name: cloudflare-warp
    state: present
