---
- name: Configure PXE boot server
  hosts: pxe
  vars:
    download_images: false # NOTE: Override via -e when refreshing ISO extracts
  roles:
    - role: lab_user
      become: true
      vars:
        lab_user_name: root
        lab_user_sudo: false
        lab_user_pubkeys: "{{ lab_authorized_pubkeys }}"
      tags: user

    - role: pxe
      become: true
