---
- name: update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: reload caddy
  ansible.builtin.service:
    name: caddy
    state: reloaded

- name: restart caddy
  ansible.builtin.service:
    name: caddy
    state: restarted

